version: '3.1'

# https://github.com/docker/awesome-compose/blob/master/official-documentation-samples/wordpress/README.md

# The docker volumes db_data and wordpress_data persists updates made by
# WordPress to the database, as well as the installed themes and plugins

services:

  wordpress:
    depends_on: 
      - db
    image: wordpress
    restart: always
    ports:
      - 8080:80
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_DB_NAME: $MYSQL_DATABASE
    volumes:
      - wp_data:/var/www/html

  db:
    image: mysql
    restart: always
    env_file: .env
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wp_data:
  db_data:
