version: "3.9"
services:
  nginx:
    image: nginx:mainline-alpine
    depends_on:
      - wordpress
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - html_data:/var/www/html

  wordpress:
    build: ./docker/wordpress
    depends_on: 
      - mysql
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_DB_NAME: $MYSQL_DATABASE
    expose:
      - 9000
    volumes:
      - html_data:/var/www/html
      - ./themes:/var/www/html/wp-content/themes
      - ./plugins:/var/www/html/wp-content/plugins

  mysql:
    image: mysql:8.0
    env_file: .env
    expose:
      - 3306
    ports:
      - 3306:3306
    restart: always
    volumes:
      - db_data:/var/lib/mysql

  # phpmyadmin:
  #   depends_on:
  #     - db
  #   image: phpmyadmin
  #   env_file: .env
  #   environment:
  #     PMA_HOST: db
  #     PMA_USER: root
  #     PMA_PASSWORD: $MYSQL_ROOT_PASSWORD
  #   ports:
  #     - 8090:80
  #   restart: always

volumes:
  html_data:
  db_data: