FROM wordpress:fpm-alpine

RUN apk add --no-cache --virtual .build-deps $PHPIZE_DEPS linux-headers \
	&& pecl install xdebug \
	&& docker-php-ext-enable xdebug \
	&& docker-php-ext-install mysqli \
	&& apk del -f .build-deps

COPY ./xdebug.ini /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini